FROM scratch
ADD TEMPLATE_ROOTFS_FILE /
ENV LANG=en_US.UTF-8
# Ensure keys are up to date
# RUN pacman-key --init && \
RUN pacman-key --init && \
    pacman-key --populate && \
    pacman-key --recv-keys B024DCEFADEF4328B5E3A848E7E0F2B78484DACF && \
    pacman-key --lsign-key B024DCEFADEF4328B5E3A848E7E0F2B78484DACF && \
    pacman -Syy --noconfirm && \
    pacman -Syu --noconfirm archlinux-keyring berserk-keyring chaotic-keyring blackarch-keyring

CMD ["/usr/bin/bash"]
