name: Publish on Manual Trigger

on:
  workflow_dispatch:

env:
  NOVNC_IMG: novnc
  BASE_DEVEL_IMG: base-devel
  LATEST_IMG: latest
  BASE_IMG: base

jobs:
  push:
    runs-on: ubuntu-latest
    container:
      image: docker.io/berserkarch/berserkarch:base-devel

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo pacman-key --init && \
          sudo pacman-key --populate && \
          sudo pacman -Sy --noconfirm --needed berserk-keyring blackarch-keyring chaotic-keyring && \
          sudo pacman -Syu --noconfirm --needed make docker devtools fakeroot fakechroot

      - name: Build base
        run: |
          make berserkarch-base
          docker tag berserkarch/berserkarch:base docker.io/berserkarch/berserkarch:$BASE_IMG
          docker tag berserkarch/berserkarch:base docker.io/berserkarch/berserkarch:$LATEST_IMG

      - name: Build base-devel
        run: |
          make berserkarch-base-devel
          docker tag berserkarch/berserkarch:base-devel docker.io/berserkarch/berserkarch:$BASE_DEVEL_IMG

      - name: Build novnc
        run: |
          docker build ./berserk-novnc --file ./berserk-novnc/Dockerfile --tag docker.io/berserkarch/berserkarch:$NOVNC_IMG

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push image
        run: |
          docker push docker.io/berserkarch/berserkarch:$NOVNC_IMG
          docker push docker.io/berserkarch/berserkarch:$BASE_IMG
          docker push docker.io/berserkarch/berserkarch:$BASE_DEVEL_IMG
          docker push docker.io/berserkarch/berserkarch:$LATEST_IMG
